### ISSUE TITLE
Membership Function

### ISSUE THREAD

**Issue by Susi-Eva** [aresio/simpful#17]
<img width="553" alt="image" src="https://user-images.githubusercontent.com/33474783/220343456-bc358a28-70d8-4c30-873d-4195520c81b7.png">
How it can be a **triangular MF**, when **a=0, b=0.5, c=1**?

**Comment by aresio** [comment]
Dear Susi, 

the coordinates of the vertices of the default normalized triangle (e.g., the one represented in the figure) are the following:
- leftmost vertex (a): (0, 0), 
- upper vertex (b): (0,5, 1)
- rightmost vertex (c): (1, 0)

Simpful automatically assumes the membership values for these vertices (i.e., the y coordinates) since it is normalized. The user only has to specify the x coordinates, In this case they are a=0, b=0.5 and c=1. I hope this clarifies the mechanism of Triangular_MF.
