### ISSUE TITLE
Doubt about replacing rules

### ISSUE THREAD

**Issue by JoseVinicius1998** [aresio/simpful#19]
I'm doing a digital twin with fuzzy logic. Anyways, sometimes I need to replace a rule for another that represents better the dynamic of the system. Is it possible to do this replacement without load all the rules every time I need to update the rules? It's different of just "append" the rules, I would need a way to replace a specific rule for another.

I thank you for the package, it's very simple to use and I already thank you for the attention!

**Comment by sspola** [comment]
Hi @JoseVinicius1998 , thanks for your interest in simpful!
@aresio just added a new method to the `FuzzySystem` object that allows you to replace rules.

It works like this:
`FS.replace_rule(i=1, rule="IF (oxygen IS high) THEN (power IS medium)")`

where `i` is the index of the rule to be substituted. Rules are stored in the object in the same order as they are added.
You can also check the current rule base with `get_rules`.

**Comment by JoseVinicius1998** [comment]
Excellent, that's very important to save time during update the system's rule. And, another asking: what is the fastest way to defuzzy the system's inputs? I'm using the Mandani_inference() method. It's very strong method, but a little slow to my application, once i have 6 inputs (yes, i know, that's a little much) and i'm spending about 2 seconds to defuzzy

**Comment by sspola** [comment]
At the moment Mamdani inference supports only the centre of gravity defuzzification, which requires the calculation of areas covered by the fuzzy sets.
This operation is quite time consuming, thus it might increase your computational time, especially with several inputs.

You can make it faster (at the expense of accuracy) with the [`subdivisions`](https://simpful.readthedocs.io/en/latest/simpful_module.html?highlight=mamdani#simpful.simpful.F) argument (the default is 1000).
Otherwise you can try to convert your model to a Takagi Sugeno system (which is computationally more efficient).
